servers:
  - name: VPS1
    host: 10.3.152.2
    user: postgres
    password: gripopdata

  - name: VPS3
    host: 10.3.152.9
    user: postgres
    password: TQwSTtLM9bSaLD

catalog_db:
  host: localhost
  dbname: data_catalog
  user: catalog_admin
  password: u698zPsMA7q9g

tools:
  pbi_tools_path: C:/tools/pbi-tools/pbi-tools.exe
