servers:
  - name: VPS1
    host: 10.3.152.2
    user: postgres
    password: ${SERVER1_PASSWORD}

  - name: VPS3
    host: 10.3.152.9
    user: postgres
    password: ${SERVER2_PASSWORD}

catalog_db:
  host: localhost
  dbname: data_catalog
  user: catalog_admin
  password: ${CATALOG_DB_PASSWORD}
